apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-laravel-5
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/joaquinrojo/docker4laravel-production-infraestructure.git'
    targetRevision: HEAD
    path: dev
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: myapp-laravel-5

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true